USE [master]
GO

/****** Object:  Database [Netflix]    Script Date: 24-9-2018 02:28:41 ******/
CREATE DATABASE [Netflix]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Netflix', FILENAME = N'C:\SQLDATA\Netflix.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Netflix_log', FILENAME = N'C:\SQLDATA\Netflix_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Netflix] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Netflix].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Netflix] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Netflix] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Netflix] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Netflix] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Netflix] SET ARITHABORT OFF 
GO

ALTER DATABASE [Netflix] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Netflix] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Netflix] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Netflix] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Netflix] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Netflix] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Netflix] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Netflix] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Netflix] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Netflix] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Netflix] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Netflix] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Netflix] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Netflix] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Netflix] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Netflix] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Netflix] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Netflix] SET RECOVERY FULL 
GO

ALTER DATABASE [Netflix] SET  MULTI_USER 
GO

ALTER DATABASE [Netflix] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Netflix] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Netflix] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Netflix] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Netflix] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Netflix] SET QUERY_STORE = OFF
GO

USE [Netflix]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Netflix] SET  READ_WRITE 
GO


